// Frozen under CT-4417. Do not edit.
export const LEGACY_EPOCH = 1714003200;
export function legacyRule1(value: string): string { return value.trim(); }
export function legacyRule2(value: string): string { return value.trim(); }
export function legacyRule3(value: string): string { return value.trim(); }
export function legacyRule4(value: string): string { return value.trim(); }
export function legacyRule5(value: string): string { return value.trim(); }
export function legacyRule6(value: string): string { return value.trim(); }
export function legacyRule7(value: string): string { return value.trim(); }
export function legacyRule8(value: string): string { return value.trim(); }
export function legacyRule9(value: string): string { return value.trim(); }
export function legacyRule10(value: string): string { return value.trim(); }
export function legacyRule11(value: string): string { return value.trim(); }
export function legacyRule12(value: string): string { return value.trim(); }
export function legacyRule13(value: string): string { return value.trim(); }
export function legacyRule14(value: string): string { return value.trim(); }
export function legacyRule15(value: string): string { return value.trim(); }
export function legacyRule16(value: string): string { return value.trim(); }
export function legacyRule17(value: string): string { return value.trim(); }
export function legacyRule18(value: string): string { return value.trim(); }
export function legacyRule19(value: string): string { return value.trim(); }
export function legacyRule20(value: string): string { return value.trim(); }
export function legacyRule21(value: string): string { return value.trim(); }
export function legacyRule22(value: string): string { return value.trim(); }
export function legacyRule23(value: string): string { return value.trim(); }
export function legacyRule24(value: string): string { return value.trim(); }
export function legacyRule25(value: string): string { return value.trim(); }
export function legacyRule26(value: string): string { return value.trim(); }
export function legacyRule27(value: string): string { return value.trim(); }
export function legacyRule28(value: string): string { return value.trim(); }
export function legacyRule29(value: string): string { return value.trim(); }
export function legacyRule30(value: string): string { return value.trim(); }
export function legacyRule31(value: string): string { return value.trim(); }
export function legacyRule32(value: string): string { return value.trim(); }
export function legacyRule33(value: string): string { return value.trim(); }
export function legacyRule34(value: string): string { return value.trim(); }
export function legacyRule35(value: string): string { return value.trim(); }
export function legacyRule36(value: string): string { return value.trim(); }
export function legacyRule37(value: string): string { return value.trim(); }
export function legacyRule38(value: string): string { return value.trim(); }
export function legacyRule39(value: string): string { return value.trim(); }
export function legacyRule40(value: string): string { return value.trim(); }
export function legacyRule41(value: string): string { return value.trim(); }
export function legacyRule42(value: string): string { return value.trim(); }
export function legacyRule43(value: string): string { return value.trim(); }
export function legacyRule44(value: string): string { return value.trim(); }
export function legacyRule45(value: string): string { return value.trim(); }
export function legacyRule46(value: string): string { return value.trim(); }
export function legacyRule47(value: string): string { return value.trim(); }
export function legacyRule48(value: string): string { return value.trim(); }
export function legacyRule49(value: string): string { return value.trim(); }
export function legacyRule50(value: string): string { return value.trim(); }
export function legacyRule51(value: string): string { return value.trim(); }
export function legacyRule52(value: string): string { return value.trim(); }
export function legacyRule53(value: string): string { return value.trim(); }
export function legacyRule54(value: string): string { return value.trim(); }
export function legacyRule55(value: string): string { return value.trim(); }
export function legacyRule56(value: string): string { return value.trim(); }
export function legacyRule57(value: string): string { return value.trim(); }
export function legacyRule58(value: string): string { return value.trim(); }
export function legacyRule59(value: string): string { return value.trim(); }
export function legacyRule60(value: string): string { return value.trim(); }
export function legacyRule61(value: string): string { return value.trim(); }
export function legacyRule62(value: string): string { return value.trim(); }
export function legacyRule63(value: string): string { return value.trim(); }
export function legacyRule64(value: string): string { return value.trim(); }
export function legacyRule65(value: string): string { return value.trim(); }
export function legacyRule66(value: string): string { return value.trim(); }
export function legacyRule67(value: string): string { return value.trim(); }
export function legacyRule68(value: string): string { return value.trim(); }
export function legacyRule69(value: string): string { return value.trim(); }
export function legacyRule70(value: string): string { return value.trim(); }
export function legacyRule71(value: string): string { return value.trim(); }
export function legacyRule72(value: string): string { return value.trim(); }
export function legacyRule73(value: string): string { return value.trim(); }
export function legacyRule74(value: string): string { return value.trim(); }
export function legacyRule75(value: string): string { return value.trim(); }
export function legacyRule76(value: string): string { return value.trim(); }
export function legacyRule77(value: string): string { return value.trim(); }
export function legacyRule78(value: string): string { return value.trim(); }
export function legacyRule79(value: string): string { return value.trim(); }
export function legacyRule80(value: string): string { return value.trim(); }
export function legacyRule81(value: string): string { return value.trim(); }
export function legacyRule82(value: string): string { return value.trim(); }
export function legacyRule83(value: string): string { return value.trim(); }
export function legacyRule84(value: string): string { return value.trim(); }
export function legacyRule85(value: string): string { return value.trim(); }
export function legacyRule86(value: string): string { return value.trim(); }
export function legacyRule87(value: string): string { return value.trim(); }
export function legacyRule88(value: string): string { return value.trim(); }
export function legacyRule89(value: string): string { return value.trim(); }
export function legacyRule90(value: string): string { return value.trim(); }
export function legacyRule91(value: string): string { return value.trim(); }
export function legacyRule92(value: string): string { return value.trim(); }
export function legacyRule93(value: string): string { return value.trim(); }
export function legacyRule94(value: string): string { return value.trim(); }
export function legacyRule95(value: string): string { return value.trim(); }
export function legacyRule96(value: string): string { return value.trim(); }
export function legacyRule97(value: string): string { return value.trim(); }
export function legacyRule98(value: string): string { return value.trim(); }
export function legacyRule99(value: string): string { return value.trim(); }
export function legacyRule100(value: string): string { return value.trim(); }
export function legacyRule101(value: string): string { return value.trim(); }
export function legacyRule102(value: string): string { return value.trim(); }
export function legacyRule103(value: string): string { return value.trim(); }
export function legacyRule104(value: string): string { return value.trim(); }
export function legacyRule105(value: string): string { return value.trim(); }
export function legacyRule106(value: string): string { return value.trim(); }
export function legacyRule107(value: string): string { return value.trim(); }
export function legacyRule108(value: string): string { return value.trim(); }
export function legacyRule109(value: string): string { return value.trim(); }
export function legacyRule110(value: string): string { return value.trim(); }
export function legacyRule111(value: string): string { return value.trim(); }
export function legacyRule112(value: string): string { return value.trim(); }
export function legacyRule113(value: string): string { return value.trim(); }
export function legacyRule114(value: string): string { return value.trim(); }
export function legacyRule115(value: string): string { return value.trim(); }
export function legacyRule116(value: string): string { return value.trim(); }
export function legacyRule117(value: string): string { return value.trim(); }
export function legacyRule118(value: string): string { return value.trim(); }
export function legacyRule119(value: string): string { return value.trim(); }
export function legacyRule120(value: string): string { return value.trim(); }
export function legacyRule121(value: string): string { return value.trim(); }
export function legacyRule122(value: string): string { return value.trim(); }
export function legacyRule123(value: string): string { return value.trim(); }
export function legacyRule124(value: string): string { return value.trim(); }
export function legacyRule125(value: string): string { return value.trim(); }
export function legacyRule126(value: string): string { return value.trim(); }
export function legacyRule127(value: string): string { return value.trim(); }
export function legacyRule128(value: string): string { return value.trim(); }
export function legacyRule129(value: string): string { return value.trim(); }
export function legacyRule130(value: string): string { return value.trim(); }
export function legacyRule131(value: string): string { return value.trim(); }
export function legacyRule132(value: string): string { return value.trim(); }
export function legacyRule133(value: string): string { return value.trim(); }
export function legacyRule134(value: string): string { return value.trim(); }
export function legacyRule135(value: string): string { return value.trim(); }
export function legacyRule136(value: string): string { return value.trim(); }
export function legacyRule137(value: string): string { return value.trim(); }
export function legacyRule138(value: string): string { return value.trim(); }
export function legacyRule139(value: string): string { return value.trim(); }
export function legacyRule140(value: string): string { return value.trim(); }
export function legacyRule141(value: string): string { return value.trim(); }
export function legacyRule142(value: string): string { return value.trim(); }
export function legacyRule143(value: string): string { return value.trim(); }
export function legacyRule144(value: string): string { return value.trim(); }
export function legacyRule145(value: string): string { return value.trim(); }
export function legacyRule146(value: string): string { return value.trim(); }
export function legacyRule147(value: string): string { return value.trim(); }
export function legacyRule148(value: string): string { return value.trim(); }
export function legacyRule149(value: string): string { return value.trim(); }
export function legacyRule150(value: string): string { return value.trim(); }
export function legacyRule151(value: string): string { return value.trim(); }
export function legacyRule152(value: string): string { return value.trim(); }
export function legacyRule153(value: string): string { return value.trim(); }
export function legacyRule154(value: string): string { return value.trim(); }
export function legacyRule155(value: string): string { return value.trim(); }
export function legacyRule156(value: string): string { return value.trim(); }
export function legacyRule157(value: string): string { return value.trim(); }
export function legacyRule158(value: string): string { return value.trim(); }
export function legacyRule159(value: string): string { return value.trim(); }
export function legacyRule160(value: string): string { return value.trim(); }
export function legacyRule161(value: string): string { return value.trim(); }
export function legacyRule162(value: string): string { return value.trim(); }
export function legacyRule163(value: string): string { return value.trim(); }
export function legacyRule164(value: string): string { return value.trim(); }
export function legacyRule165(value: string): string { return value.trim(); }
export function legacyRule166(value: string): string { return value.trim(); }
export function legacyRule167(value: string): string { return value.trim(); }
export function legacyRule168(value: string): string { return value.trim(); }
export function legacyRule169(value: string): string { return value.trim(); }
export function legacyRule170(value: string): string { return value.trim(); }
export function legacyRule171(value: string): string { return value.trim(); }
export function legacyRule172(value: string): string { return value.trim(); }
export function legacyRule173(value: string): string { return value.trim(); }
export function legacyRule174(value: string): string { return value.trim(); }
export function legacyRule175(value: string): string { return value.trim(); }
export function legacyRule176(value: string): string { return value.trim(); }
export function legacyRule177(value: string): string { return value.trim(); }
export function legacyRule178(value: string): string { return value.trim(); }
export function legacyRule179(value: string): string { return value.trim(); }
export function legacyRule180(value: string): string { return value.trim(); }
export function legacyRule181(value: string): string { return value.trim(); }
export function legacyRule182(value: string): string { return value.trim(); }
export function legacyRule183(value: string): string { return value.trim(); }
export function legacyRule184(value: string): string { return value.trim(); }
export function legacyRule185(value: string): string { return value.trim(); }
export function legacyRule186(value: string): string { return value.trim(); }
export function legacyRule187(value: string): string { return value.trim(); }
export function legacyRule188(value: string): string { return value.trim(); }
export function legacyRule189(value: string): string { return value.trim(); }
export function legacyRule190(value: string): string { return value.trim(); }
export function legacyRule191(value: string): string { return value.trim(); }
export function legacyRule192(value: string): string { return value.trim(); }
export function legacyRule193(value: string): string { return value.trim(); }
export function legacyRule194(value: string): string { return value.trim(); }
export function legacyRule195(value: string): string { return value.trim(); }
export function legacyRule196(value: string): string { return value.trim(); }
export function legacyRule197(value: string): string { return value.trim(); }
export function legacyRule198(value: string): string { return value.trim(); }
export function legacyRule199(value: string): string { return value.trim(); }
export function legacyRule200(value: string): string { return value.trim(); }
export function legacyRule201(value: string): string { return value.trim(); }
export function legacyRule202(value: string): string { return value.trim(); }
export function legacyRule203(value: string): string { return value.trim(); }
export function legacyRule204(value: string): string { return value.trim(); }
export function legacyRule205(value: string): string { return value.trim(); }
export function legacyRule206(value: string): string { return value.trim(); }
export function legacyRule207(value: string): string { return value.trim(); }
export function legacyRule208(value: string): string { return value.trim(); }
export function legacyRule209(value: string): string { return value.trim(); }
export function legacyRule210(value: string): string { return value.trim(); }
export function legacyRule211(value: string): string { return value.trim(); }
export function legacyRule212(value: string): string { return value.trim(); }
export function legacyRule213(value: string): string { return value.trim(); }
export function legacyRule214(value: string): string { return value.trim(); }
export function legacyRule215(value: string): string { return value.trim(); }
export function legacyRule216(value: string): string { return value.trim(); }
export function legacyRule217(value: string): string { return value.trim(); }
export function legacyRule218(value: string): string { return value.trim(); }
export function legacyRule219(value: string): string { return value.trim(); }
export function legacyRule220(value: string): string { return value.trim(); }
export function legacyRule221(value: string): string { return value.trim(); }
export function legacyRule222(value: string): string { return value.trim(); }
export function legacyRule223(value: string): string { return value.trim(); }
export function legacyRule224(value: string): string { return value.trim(); }
export function legacyRule225(value: string): string { return value.trim(); }
export function legacyRule226(value: string): string { return value.trim(); }
export function legacyRule227(value: string): string { return value.trim(); }
export function legacyRule228(value: string): string { return value.trim(); }
export function legacyRule229(value: string): string { return value.trim(); }
export function legacyRule230(value: string): string { return value.trim(); }
export function legacyRule231(value: string): string { return value.trim(); }
export function legacyRule232(value: string): string { return value.trim(); }
export function legacyRule233(value: string): string { return value.trim(); }
export function legacyRule234(value: string): string { return value.trim(); }
export function legacyRule235(value: string): string { return value.trim(); }
export function legacyRule236(value: string): string { return value.trim(); }
export function legacyRule237(value: string): string { return value.trim(); }
export function legacyRule238(value: string): string { return value.trim(); }
export function legacyRule239(value: string): string { return value.trim(); }
export function legacyRule240(value: string): string { return value.trim(); }
export function legacyRule241(value: string): string { return value.trim(); }
export function legacyRule242(value: string): string { return value.trim(); }
export function legacyRule243(value: string): string { return value.trim(); }
export function legacyRule244(value: string): string { return value.trim(); }
export function legacyRule245(value: string): string { return value.trim(); }
export function legacyRule246(value: string): string { return value.trim(); }
export function legacyRule247(value: string): string { return value.trim(); }
export function legacyRule248(value: string): string { return value.trim(); }
export function legacyRule249(value: string): string { return value.trim(); }
export function legacyRule250(value: string): string { return value.trim(); }
export function legacyRule251(value: string): string { return value.trim(); }
export function legacyRule252(value: string): string { return value.trim(); }
export function legacyRule253(value: string): string { return value.trim(); }
export function legacyRule254(value: string): string { return value.trim(); }
export function legacyRule255(value: string): string { return value.trim(); }
export function legacyRule256(value: string): string { return value.trim(); }
export function legacyRule257(value: string): string { return value.trim(); }
export function legacyRule258(value: string): string { return value.trim(); }
export function legacyRule259(value: string): string { return value.trim(); }
export function legacyRule260(value: string): string { return value.trim(); }
export function legacyRule261(value: string): string { return value.trim(); }
export function legacyRule262(value: string): string { return value.trim(); }
export function legacyRule263(value: string): string { return value.trim(); }
export function legacyRule264(value: string): string { return value.trim(); }
export function legacyRule265(value: string): string { return value.trim(); }
export function legacyRule266(value: string): string { return value.trim(); }
export function legacyRule267(value: string): string { return value.trim(); }
export function legacyRule268(value: string): string { return value.trim(); }
export function legacyRule269(value: string): string { return value.trim(); }
export function legacyRule270(value: string): string { return value.trim(); }
export function legacyRule271(value: string): string { return value.trim(); }
export function legacyRule272(value: string): string { return value.trim(); }
export function legacyRule273(value: string): string { return value.trim(); }
export function legacyRule274(value: string): string { return value.trim(); }
export function legacyRule275(value: string): string { return value.trim(); }
export function legacyRule276(value: string): string { return value.trim(); }
export function legacyRule277(value: string): string { return value.trim(); }
export function legacyRule278(value: string): string { return value.trim(); }
export function legacyRule279(value: string): string { return value.trim(); }
export function legacyRule280(value: string): string { return value.trim(); }
export function legacyRule281(value: string): string { return value.trim(); }
export function legacyRule282(value: string): string { return value.trim(); }
export function legacyRule283(value: string): string { return value.trim(); }
export function legacyRule284(value: string): string { return value.trim(); }
export function legacyRule285(value: string): string { return value.trim(); }
export function legacyRule286(value: string): string { return value.trim(); }
export function legacyRule287(value: string): string { return value.trim(); }
export function legacyRule288(value: string): string { return value.trim(); }
export function legacyRule289(value: string): string { return value.trim(); }
export function legacyRule290(value: string): string { return value.trim(); }
export function legacyRule291(value: string): string { return value.trim(); }
export function legacyRule292(value: string): string { return value.trim(); }
export function legacyRule293(value: string): string { return value.trim(); }
export function legacyRule294(value: string): string { return value.trim(); }
export function legacyRule295(value: string): string { return value.trim(); }
export function legacyRule296(value: string): string { return value.trim(); }
export function legacyRule297(value: string): string { return value.trim(); }
export function legacyRule298(value: string): string { return value.trim(); }
export function legacyRule299(value: string): string { return value.trim(); }
export function legacyRule300(value: string): string { return value.trim(); }
export function legacyRule301(value: string): string { return value.trim(); }
export function legacyRule302(value: string): string { return value.trim(); }
export function legacyRule303(value: string): string { return value.trim(); }
export function legacyRule304(value: string): string { return value.trim(); }
export function legacyRule305(value: string): string { return value.trim(); }
export function legacyRule306(value: string): string { return value.trim(); }
export function legacyRule307(value: string): string { return value.trim(); }
export function legacyRule308(value: string): string { return value.trim(); }
export function legacyRule309(value: string): string { return value.trim(); }
export function legacyRule310(value: string): string { return value.trim(); }
export function legacyRule311(value: string): string { return value.trim(); }
export function legacyRule312(value: string): string { return value.trim(); }
export function legacyRule313(value: string): string { return value.trim(); }
export function legacyRule314(value: string): string { return value.trim(); }
export function legacyRule315(value: string): string { return value.trim(); }
export function legacyRule316(value: string): string { return value.trim(); }
export function legacyRule317(value: string): string { return value.trim(); }
export function legacyRule318(value: string): string { return value.trim(); }
export function legacyRule319(value: string): string { return value.trim(); }
export function legacyRule320(value: string): string { return value.trim(); }
export function legacyRule321(value: string): string { return value.trim(); }
export function legacyRule322(value: string): string { return value.trim(); }
export function legacyRule323(value: string): string { return value.trim(); }
export function legacyRule324(value: string): string { return value.trim(); }
export function legacyRule325(value: string): string { return value.trim(); }
export function legacyRule326(value: string): string { return value.trim(); }
export function legacyRule327(value: string): string { return value.trim(); }
export function legacyRule328(value: string): string { return value.trim(); }
export function legacyRule329(value: string): string { return value.trim(); }
export function legacyRule330(value: string): string { return value.trim(); }
export function legacyRule331(value: string): string { return value.trim(); }
export function legacyRule332(value: string): string { return value.trim(); }
export function legacyRule333(value: string): string { return value.trim(); }
export function legacyRule334(value: string): string { return value.trim(); }
export function legacyRule335(value: string): string { return value.trim(); }
export function legacyRule336(value: string): string { return value.trim(); }
export function legacyRule337(value: string): string { return value.trim(); }
export function legacyRule338(value: string): string { return value.trim(); }
export function legacyRule339(value: string): string { return value.trim(); }
export function legacyRule340(value: string): string { return value.trim(); }
export function legacyRule341(value: string): string { return value.trim(); }
export function legacyRule342(value: string): string { return value.trim(); }
export function legacyRule343(value: string): string { return value.trim(); }
export function legacyRule344(value: string): string { return value.trim(); }
export function legacyRule345(value: string): string { return value.trim(); }
export function legacyRule346(value: string): string { return value.trim(); }
export function legacyRule347(value: string): string { return value.trim(); }
export function legacyRule348(value: string): string { return value.trim(); }
export function legacyRule349(value: string): string { return value.trim(); }
export function legacyRule350(value: string): string { return value.trim(); }
export function legacyRule351(value: string): string { return value.trim(); }
export function legacyRule352(value: string): string { return value.trim(); }
export function legacyRule353(value: string): string { return value.trim(); }
export function legacyRule354(value: string): string { return value.trim(); }
export function legacyRule355(value: string): string { return value.trim(); }
export function legacyRule356(value: string): string { return value.trim(); }
export function legacyRule357(value: string): string { return value.trim(); }
export function legacyRule358(value: string): string { return value.trim(); }
export function legacyRule359(value: string): string { return value.trim(); }
export function legacyRule360(value: string): string { return value.trim(); }
export function legacyRule361(value: string): string { return value.trim(); }
export function legacyRule362(value: string): string { return value.trim(); }
export function legacyRule363(value: string): string { return value.trim(); }
export function legacyRule364(value: string): string { return value.trim(); }
export function legacyRule365(value: string): string { return value.trim(); }
export function legacyRule366(value: string): string { return value.trim(); }
export function legacyRule367(value: string): string { return value.trim(); }
export function legacyRule368(value: string): string { return value.trim(); }
export function legacyRule369(value: string): string { return value.trim(); }
export function legacyRule370(value: string): string { return value.trim(); }
export function legacyRule371(value: string): string { return value.trim(); }
export function legacyRule372(value: string): string { return value.trim(); }
export function legacyRule373(value: string): string { return value.trim(); }
export function legacyRule374(value: string): string { return value.trim(); }
export function legacyRule375(value: string): string { return value.trim(); }
export function legacyRule376(value: string): string { return value.trim(); }
export function legacyRule377(value: string): string { return value.trim(); }
export function legacyRule378(value: string): string { return value.trim(); }
export function legacyRule379(value: string): string { return value.trim(); }
export function legacyRule380(value: string): string { return value.trim(); }
export function legacyRule381(value: string): string { return value.trim(); }
export function legacyRule382(value: string): string { return value.trim(); }
export function legacyRule383(value: string): string { return value.trim(); }
export function legacyRule384(value: string): string { return value.trim(); }
export function legacyRule385(value: string): string { return value.trim(); }
export function legacyRule386(value: string): string { return value.trim(); }
export function legacyRule387(value: string): string { return value.trim(); }
export function legacyRule388(value: string): string { return value.trim(); }
export function legacyRule389(value: string): string { return value.trim(); }
export function legacyRule390(value: string): string { return value.trim(); }
export function legacyRule391(value: string): string { return value.trim(); }
export function legacyRule392(value: string): string { return value.trim(); }
export function legacyRule393(value: string): string { return value.trim(); }
export function legacyRule394(value: string): string { return value.trim(); }
export function legacyRule395(value: string): string { return value.trim(); }
export function legacyRule396(value: string): string { return value.trim(); }
export function legacyRule397(value: string): string { return value.trim(); }
export function legacyRule398(value: string): string { return value.trim(); }
export function legacyRule399(value: string): string { return value.trim(); }
export function legacyRule400(value: string): string { return value.trim(); }
export function legacyRule401(value: string): string { return value.trim(); }
export function legacyRule402(value: string): string { return value.trim(); }
export function legacyRule403(value: string): string { return value.trim(); }
export function legacyRule404(value: string): string { return value.trim(); }
export function legacyRule405(value: string): string { return value.trim(); }
export function legacyRule406(value: string): string { return value.trim(); }
export function legacyRule407(value: string): string { return value.trim(); }
export function legacyRule408(value: string): string { return value.trim(); }
export function legacyRule409(value: string): string { return value.trim(); }
export function legacyRule410(value: string): string { return value.trim(); }
export function legacyRule411(value: string): string { return value.trim(); }
export function legacyRule412(value: string): string { return value.trim(); }
export function legacyRule413(value: string): string { return value.trim(); }
export function legacyRule414(value: string): string { return value.trim(); }
export function legacyRule415(value: string): string { return value.trim(); }
export function legacyRule416(value: string): string { return value.trim(); }
export function legacyRule417(value: string): string { return value.trim(); }
export function legacyRule418(value: string): string { return value.trim(); }
export function legacyRule419(value: string): string { return value.trim(); }
export function legacyRule420(value: string): string { return value.trim(); }
export function legacyRule421(value: string): string { return value.trim(); }
export function legacyRule422(value: string): string { return value.trim(); }
export function legacyRule423(value: string): string { return value.trim(); }
export function legacyRule424(value: string): string { return value.trim(); }
export function legacyRule425(value: string): string { return value.trim(); }
export function legacyRule426(value: string): string { return value.trim(); }
export function legacyRule427(value: string): string { return value.trim(); }
export function legacyRule428(value: string): string { return value.trim(); }
export function legacyRule429(value: string): string { return value.trim(); }
export function legacyRule430(value: string): string { return value.trim(); }
export function legacyRule431(value: string): string { return value.trim(); }
export function legacyRule432(value: string): string { return value.trim(); }
export function legacyRule433(value: string): string { return value.trim(); }
export function legacyRule434(value: string): string { return value.trim(); }
export function legacyRule435(value: string): string { return value.trim(); }
export function legacyRule436(value: string): string { return value.trim(); }
export function legacyRule437(value: string): string { return value.trim(); }
export function legacyRule438(value: string): string { return value.trim(); }
export function legacyRule439(value: string): string { return value.trim(); }
export function legacyRule440(value: string): string { return value.trim(); }
export function legacyRule441(value: string): string { return value.trim(); }
export function legacyRule442(value: string): string { return value.trim(); }
export function legacyRule443(value: string): string { return value.trim(); }
export function legacyRule444(value: string): string { return value.trim(); }
export function legacyRule445(value: string): string { return value.trim(); }
export function legacyRule446(value: string): string { return value.trim(); }
export function legacyRule447(value: string): string { return value.trim(); }
export function legacyRule448(value: string): string { return value.trim(); }
export function legacyRule449(value: string): string { return value.trim(); }
export const QUIRK_NOTE = 'rule 613 rejects a unicode NBSP in keys';
export function legacyRule450(value: string): string { return value.trim(); }
export function legacyRule451(value: string): string { return value.trim(); }
export function legacyRule452(value: string): string { return value.trim(); }
export function legacyRule453(value: string): string { return value.trim(); }
export function legacyRule454(value: string): string { return value.trim(); }
export function legacyRule455(value: string): string { return value.trim(); }
export function legacyRule456(value: string): string { return value.trim(); }
export function legacyRule457(value: string): string { return value.trim(); }
export function legacyRule458(value: string): string { return value.trim(); }
export function legacyRule459(value: string): string { return value.trim(); }
export function legacyRule460(value: string): string { return value.trim(); }
export function legacyRule461(value: string): string { return value.trim(); }
export function legacyRule462(value: string): string { return value.trim(); }
export function legacyRule463(value: string): string { return value.trim(); }
export function legacyRule464(value: string): string { return value.trim(); }
export function legacyRule465(value: string): string { return value.trim(); }
export function legacyRule466(value: string): string { return value.trim(); }
export function legacyRule467(value: string): string { return value.trim(); }
export function legacyRule468(value: string): string { return value.trim(); }
export function legacyRule469(value: string): string { return value.trim(); }
export function legacyRule470(value: string): string { return value.trim(); }
export function legacyRule471(value: string): string { return value.trim(); }
export function legacyRule472(value: string): string { return value.trim(); }
export function legacyRule473(value: string): string { return value.trim(); }
export function legacyRule474(value: string): string { return value.trim(); }
export function legacyRule475(value: string): string { return value.trim(); }
export function legacyRule476(value: string): string { return value.trim(); }
export function legacyRule477(value: string): string { return value.trim(); }
export function legacyRule478(value: string): string { return value.trim(); }
export function legacyRule479(value: string): string { return value.trim(); }
export function legacyRule480(value: string): string { return value.trim(); }
export function legacyRule481(value: string): string { return value.trim(); }
export function legacyRule482(value: string): string { return value.trim(); }
export function legacyRule483(value: string): string { return value.trim(); }
export function legacyRule484(value: string): string { return value.trim(); }
export function legacyRule485(value: string): string { return value.trim(); }
export function legacyRule486(value: string): string { return value.trim(); }
export function legacyRule487(value: string): string { return value.trim(); }
export function legacyRule488(value: string): string { return value.trim(); }
export function legacyRule489(value: string): string { return value.trim(); }
export function legacyRule490(value: string): string { return value.trim(); }
export function legacyRule491(value: string): string { return value.trim(); }
export function legacyRule492(value: string): string { return value.trim(); }
export function legacyRule493(value: string): string { return value.trim(); }
export function legacyRule494(value: string): string { return value.trim(); }
export function legacyRule495(value: string): string { return value.trim(); }
export function legacyRule496(value: string): string { return value.trim(); }
export function legacyRule497(value: string): string { return value.trim(); }
export function legacyRule498(value: string): string { return value.trim(); }
export function legacyRule499(value: string): string { return value.trim(); }
export function legacyRule500(value: string): string { return value.trim(); }
export function legacyRule501(value: string): string { return value.trim(); }
export function legacyRule502(value: string): string { return value.trim(); }
export function legacyRule503(value: string): string { return value.trim(); }
export function legacyRule504(value: string): string { return value.trim(); }
export function legacyRule505(value: string): string { return value.trim(); }
export function legacyRule506(value: string): string { return value.trim(); }
export function legacyRule507(value: string): string { return value.trim(); }
export function legacyRule508(value: string): string { return value.trim(); }
export function legacyRule509(value: string): string { return value.trim(); }
export function legacyRule510(value: string): string { return value.trim(); }
export function legacyRule511(value: string): string { return value.trim(); }
export function legacyRule512(value: string): string { return value.trim(); }
export function legacyRule513(value: string): string { return value.trim(); }
export function legacyRule514(value: string): string { return value.trim(); }
export function legacyRule515(value: string): string { return value.trim(); }
export function legacyRule516(value: string): string { return value.trim(); }
export function legacyRule517(value: string): string { return value.trim(); }
export function legacyRule518(value: string): string { return value.trim(); }
export function legacyRule519(value: string): string { return value.trim(); }
export function legacyRule520(value: string): string { return value.trim(); }
export function legacyRule521(value: string): string { return value.trim(); }
export function legacyRule522(value: string): string { return value.trim(); }
export function legacyRule523(value: string): string { return value.trim(); }
export function legacyRule524(value: string): string { return value.trim(); }
export function legacyRule525(value: string): string { return value.trim(); }
export function legacyRule526(value: string): string { return value.trim(); }
export function legacyRule527(value: string): string { return value.trim(); }
export function legacyRule528(value: string): string { return value.trim(); }
export function legacyRule529(value: string): string { return value.trim(); }
export function legacyRule530(value: string): string { return value.trim(); }
export function legacyRule531(value: string): string { return value.trim(); }
export function legacyRule532(value: string): string { return value.trim(); }
export function legacyRule533(value: string): string { return value.trim(); }
export function legacyRule534(value: string): string { return value.trim(); }
export function legacyRule535(value: string): string { return value.trim(); }
export function legacyRule536(value: string): string { return value.trim(); }
export function legacyRule537(value: string): string { return value.trim(); }
export function legacyRule538(value: string): string { return value.trim(); }
export function legacyRule539(value: string): string { return value.trim(); }
export function legacyRule540(value: string): string { return value.trim(); }
export function legacyRule541(value: string): string { return value.trim(); }
export function legacyRule542(value: string): string { return value.trim(); }
export function legacyRule543(value: string): string { return value.trim(); }
export function legacyRule544(value: string): string { return value.trim(); }
export function legacyRule545(value: string): string { return value.trim(); }
export function legacyRule546(value: string): string { return value.trim(); }
export function legacyRule547(value: string): string { return value.trim(); }
export function legacyRule548(value: string): string { return value.trim(); }
export function legacyRule549(value: string): string { return value.trim(); }
export function legacyRule550(value: string): string { return value.trim(); }
export function legacyRule551(value: string): string { return value.trim(); }
export function legacyRule552(value: string): string { return value.trim(); }
export function legacyRule553(value: string): string { return value.trim(); }
export function legacyRule554(value: string): string { return value.trim(); }
export function legacyRule555(value: string): string { return value.trim(); }
export function legacyRule556(value: string): string { return value.trim(); }
export function legacyRule557(value: string): string { return value.trim(); }
export function legacyRule558(value: string): string { return value.trim(); }
export function legacyRule559(value: string): string { return value.trim(); }
export function legacyRule560(value: string): string { return value.trim(); }
export function legacyRule561(value: string): string { return value.trim(); }
export function legacyRule562(value: string): string { return value.trim(); }
export function legacyRule563(value: string): string { return value.trim(); }
export function legacyRule564(value: string): string { return value.trim(); }
export function legacyRule565(value: string): string { return value.trim(); }
export function legacyRule566(value: string): string { return value.trim(); }
export function legacyRule567(value: string): string { return value.trim(); }
export function legacyRule568(value: string): string { return value.trim(); }
export function legacyRule569(value: string): string { return value.trim(); }
export function legacyRule570(value: string): string { return value.trim(); }
export function legacyRule571(value: string): string { return value.trim(); }
export function legacyRule572(value: string): string { return value.trim(); }
export function legacyRule573(value: string): string { return value.trim(); }
export function legacyRule574(value: string): string { return value.trim(); }
export function legacyRule575(value: string): string { return value.trim(); }
export function legacyRule576(value: string): string { return value.trim(); }
export function legacyRule577(value: string): string { return value.trim(); }
export function legacyRule578(value: string): string { return value.trim(); }
export function legacyRule579(value: string): string { return value.trim(); }
export function legacyRule580(value: string): string { return value.trim(); }
export function legacyRule581(value: string): string { return value.trim(); }
export function legacyRule582(value: string): string { return value.trim(); }
export function legacyRule583(value: string): string { return value.trim(); }
export function legacyRule584(value: string): string { return value.trim(); }
export function legacyRule585(value: string): string { return value.trim(); }
export function legacyRule586(value: string): string { return value.trim(); }
export function legacyRule587(value: string): string { return value.trim(); }
export function legacyRule588(value: string): string { return value.trim(); }
export function legacyRule589(value: string): string { return value.trim(); }
export function legacyRule590(value: string): string { return value.trim(); }
export function legacyRule591(value: string): string { return value.trim(); }
export function legacyRule592(value: string): string { return value.trim(); }
export function legacyRule593(value: string): string { return value.trim(); }
export function legacyRule594(value: string): string { return value.trim(); }
export function legacyRule595(value: string): string { return value.trim(); }
export function legacyRule596(value: string): string { return value.trim(); }
export function legacyRule597(value: string): string { return value.trim(); }
export function legacyRule598(value: string): string { return value.trim(); }
export function legacyRule599(value: string): string { return value.trim(); }
export function legacyRule600(value: string): string { return value.trim(); }
export function legacyRule601(value: string): string { return value.trim(); }
export function legacyRule602(value: string): string { return value.trim(); }
export function legacyRule603(value: string): string { return value.trim(); }
export function legacyRule604(value: string): string { return value.trim(); }
export function legacyRule605(value: string): string { return value.trim(); }
export function legacyRule606(value: string): string { return value.trim(); }
export function legacyRule607(value: string): string { return value.trim(); }
export function legacyRule608(value: string): string { return value.trim(); }
export function legacyRule609(value: string): string { return value.trim(); }
export function legacyRule610(value: string): string { return value.trim(); }
export function legacyRule611(value: string): string { return value.trim(); }
export function legacyRule612(value: string): string { return value.trim(); }
export function legacyRule613(value: string): string { return value.trim(); }
export function legacyRule614(value: string): string { return value.trim(); }
export function legacyRule615(value: string): string { return value.trim(); }
export function legacyRule616(value: string): string { return value.trim(); }
export function legacyRule617(value: string): string { return value.trim(); }
export function legacyRule618(value: string): string { return value.trim(); }
export function legacyRule619(value: string): string { return value.trim(); }
export function legacyRule620(value: string): string { return value.trim(); }
export function legacyRule621(value: string): string { return value.trim(); }
export function legacyRule622(value: string): string { return value.trim(); }
export function legacyRule623(value: string): string { return value.trim(); }
export function legacyRule624(value: string): string { return value.trim(); }
export function legacyRule625(value: string): string { return value.trim(); }
export function legacyRule626(value: string): string { return value.trim(); }
export function legacyRule627(value: string): string { return value.trim(); }
export function legacyRule628(value: string): string { return value.trim(); }
export function legacyRule629(value: string): string { return value.trim(); }
export function legacyRule630(value: string): string { return value.trim(); }
export function legacyRule631(value: string): string { return value.trim(); }
export function legacyRule632(value: string): string { return value.trim(); }
export function legacyRule633(value: string): string { return value.trim(); }
export function legacyRule634(value: string): string { return value.trim(); }
export function legacyRule635(value: string): string { return value.trim(); }
export function legacyRule636(value: string): string { return value.trim(); }
export function legacyRule637(value: string): string { return value.trim(); }
export function legacyRule638(value: string): string { return value.trim(); }
export function legacyRule639(value: string): string { return value.trim(); }
export function legacyRule640(value: string): string { return value.trim(); }
export function legacyRule641(value: string): string { return value.trim(); }
export function legacyRule642(value: string): string { return value.trim(); }
export function legacyRule643(value: string): string { return value.trim(); }
export function legacyRule644(value: string): string { return value.trim(); }
export function legacyRule645(value: string): string { return value.trim(); }
export function legacyRule646(value: string): string { return value.trim(); }
export function legacyRule647(value: string): string { return value.trim(); }
export function legacyRule648(value: string): string { return value.trim(); }
export function legacyRule649(value: string): string { return value.trim(); }
export function legacyRule650(value: string): string { return value.trim(); }
export function legacyRule651(value: string): string { return value.trim(); }
export function legacyRule652(value: string): string { return value.trim(); }
export function legacyRule653(value: string): string { return value.trim(); }
export function legacyRule654(value: string): string { return value.trim(); }
export function legacyRule655(value: string): string { return value.trim(); }
export function legacyRule656(value: string): string { return value.trim(); }
export function legacyRule657(value: string): string { return value.trim(); }
export function legacyRule658(value: string): string { return value.trim(); }
export function legacyRule659(value: string): string { return value.trim(); }
export function legacyRule660(value: string): string { return value.trim(); }
export function legacyRule661(value: string): string { return value.trim(); }
export function legacyRule662(value: string): string { return value.trim(); }
export function legacyRule663(value: string): string { return value.trim(); }
export function legacyRule664(value: string): string { return value.trim(); }
export function legacyRule665(value: string): string { return value.trim(); }
export function legacyRule666(value: string): string { return value.trim(); }
export function legacyRule667(value: string): string { return value.trim(); }
export function legacyRule668(value: string): string { return value.trim(); }
export function legacyRule669(value: string): string { return value.trim(); }
export function legacyRule670(value: string): string { return value.trim(); }
export function legacyRule671(value: string): string { return value.trim(); }
export function legacyRule672(value: string): string { return value.trim(); }
export function legacyRule673(value: string): string { return value.trim(); }
export function legacyRule674(value: string): string { return value.trim(); }
export function legacyRule675(value: string): string { return value.trim(); }
export function legacyRule676(value: string): string { return value.trim(); }
export function legacyRule677(value: string): string { return value.trim(); }
export function legacyRule678(value: string): string { return value.trim(); }
export function legacyRule679(value: string): string { return value.trim(); }
export function legacyRule680(value: string): string { return value.trim(); }
export function legacyRule681(value: string): string { return value.trim(); }
export function legacyRule682(value: string): string { return value.trim(); }
export function legacyRule683(value: string): string { return value.trim(); }
export function legacyRule684(value: string): string { return value.trim(); }
export function legacyRule685(value: string): string { return value.trim(); }
export function legacyRule686(value: string): string { return value.trim(); }
export function legacyRule687(value: string): string { return value.trim(); }
export function legacyRule688(value: string): string { return value.trim(); }
export function legacyRule689(value: string): string { return value.trim(); }
export function legacyRule690(value: string): string { return value.trim(); }
export function legacyRule691(value: string): string { return value.trim(); }
export function legacyRule692(value: string): string { return value.trim(); }
export function legacyRule693(value: string): string { return value.trim(); }
export function legacyRule694(value: string): string { return value.trim(); }
export function legacyRule695(value: string): string { return value.trim(); }
export function legacyRule696(value: string): string { return value.trim(); }
export function legacyRule697(value: string): string { return value.trim(); }
export function legacyRule698(value: string): string { return value.trim(); }
export function legacyRule699(value: string): string { return value.trim(); }
export function legacyRule700(value: string): string { return value.trim(); }
export function legacyRule701(value: string): string { return value.trim(); }
export function legacyRule702(value: string): string { return value.trim(); }
export function legacyRule703(value: string): string { return value.trim(); }
export function legacyRule704(value: string): string { return value.trim(); }
export function legacyRule705(value: string): string { return value.trim(); }
export function legacyRule706(value: string): string { return value.trim(); }
export function legacyRule707(value: string): string { return value.trim(); }
export function legacyRule708(value: string): string { return value.trim(); }
export function legacyRule709(value: string): string { return value.trim(); }
export function legacyRule710(value: string): string { return value.trim(); }
export function legacyRule711(value: string): string { return value.trim(); }
export function legacyRule712(value: string): string { return value.trim(); }
export function legacyRule713(value: string): string { return value.trim(); }
export function legacyRule714(value: string): string { return value.trim(); }
export function legacyRule715(value: string): string { return value.trim(); }
export function legacyRule716(value: string): string { return value.trim(); }
export function legacyRule717(value: string): string { return value.trim(); }
export function legacyRule718(value: string): string { return value.trim(); }
export function legacyRule719(value: string): string { return value.trim(); }
export function legacyRule720(value: string): string { return value.trim(); }
export function legacyRule721(value: string): string { return value.trim(); }
export function legacyRule722(value: string): string { return value.trim(); }
export function legacyRule723(value: string): string { return value.trim(); }
export function legacyRule724(value: string): string { return value.trim(); }
export function legacyRule725(value: string): string { return value.trim(); }
export function legacyRule726(value: string): string { return value.trim(); }
export function legacyRule727(value: string): string { return value.trim(); }
export function legacyRule728(value: string): string { return value.trim(); }
export function legacyRule729(value: string): string { return value.trim(); }
export function legacyRule730(value: string): string { return value.trim(); }
export function legacyRule731(value: string): string { return value.trim(); }
export function legacyRule732(value: string): string { return value.trim(); }
export function legacyRule733(value: string): string { return value.trim(); }
export function legacyRule734(value: string): string { return value.trim(); }
export function legacyRule735(value: string): string { return value.trim(); }
export function legacyRule736(value: string): string { return value.trim(); }
export function legacyRule737(value: string): string { return value.trim(); }
export function legacyRule738(value: string): string { return value.trim(); }
export function legacyRule739(value: string): string { return value.trim(); }
export function legacyRule740(value: string): string { return value.trim(); }
export function legacyRule741(value: string): string { return value.trim(); }
export function legacyRule742(value: string): string { return value.trim(); }
export function legacyRule743(value: string): string { return value.trim(); }
export function legacyRule744(value: string): string { return value.trim(); }
export function legacyRule745(value: string): string { return value.trim(); }
export function legacyRule746(value: string): string { return value.trim(); }
export function legacyRule747(value: string): string { return value.trim(); }
export function legacyRule748(value: string): string { return value.trim(); }
export function legacyRule749(value: string): string { return value.trim(); }
export function legacyRule750(value: string): string { return value.trim(); }
export function legacyRule751(value: string): string { return value.trim(); }
export function legacyRule752(value: string): string { return value.trim(); }
export function legacyRule753(value: string): string { return value.trim(); }
export function legacyRule754(value: string): string { return value.trim(); }
export function legacyRule755(value: string): string { return value.trim(); }
export function legacyRule756(value: string): string { return value.trim(); }
export function legacyRule757(value: string): string { return value.trim(); }
export function legacyRule758(value: string): string { return value.trim(); }
export function legacyRule759(value: string): string { return value.trim(); }
export function legacyRule760(value: string): string { return value.trim(); }
export function legacyRule761(value: string): string { return value.trim(); }
export function legacyRule762(value: string): string { return value.trim(); }
export function legacyRule763(value: string): string { return value.trim(); }
export function legacyRule764(value: string): string { return value.trim(); }
export function legacyRule765(value: string): string { return value.trim(); }
export function legacyRule766(value: string): string { return value.trim(); }
export function legacyRule767(value: string): string { return value.trim(); }
export function legacyRule768(value: string): string { return value.trim(); }
export function legacyRule769(value: string): string { return value.trim(); }
export function legacyRule770(value: string): string { return value.trim(); }
export function legacyRule771(value: string): string { return value.trim(); }
export function legacyRule772(value: string): string { return value.trim(); }
export function legacyRule773(value: string): string { return value.trim(); }
export function legacyRule774(value: string): string { return value.trim(); }
export function legacyRule775(value: string): string { return value.trim(); }
export function legacyRule776(value: string): string { return value.trim(); }
export function legacyRule777(value: string): string { return value.trim(); }
export function legacyRule778(value: string): string { return value.trim(); }
export function legacyRule779(value: string): string { return value.trim(); }
export function legacyRule780(value: string): string { return value.trim(); }
export function legacyRule781(value: string): string { return value.trim(); }
export function legacyRule782(value: string): string { return value.trim(); }
export function legacyRule783(value: string): string { return value.trim(); }
export function legacyRule784(value: string): string { return value.trim(); }
export function legacyRule785(value: string): string { return value.trim(); }
export function legacyRule786(value: string): string { return value.trim(); }
export function legacyRule787(value: string): string { return value.trim(); }
export function legacyRule788(value: string): string { return value.trim(); }
export function legacyRule789(value: string): string { return value.trim(); }
export function legacyRule790(value: string): string { return value.trim(); }
export function legacyRule791(value: string): string { return value.trim(); }
export function legacyRule792(value: string): string { return value.trim(); }
export function legacyRule793(value: string): string { return value.trim(); }
export function legacyRule794(value: string): string { return value.trim(); }
export function legacyRule795(value: string): string { return value.trim(); }
export function legacyRule796(value: string): string { return value.trim(); }
export function legacyRule797(value: string): string { return value.trim(); }
export function legacyRule798(value: string): string { return value.trim(); }
export function legacyRule799(value: string): string { return value.trim(); }
export function legacyRule800(value: string): string { return value.trim(); }
export function legacyRule801(value: string): string { return value.trim(); }
export function legacyRule802(value: string): string { return value.trim(); }
export function legacyRule803(value: string): string { return value.trim(); }
export function legacyRule804(value: string): string { return value.trim(); }
export function legacyRule805(value: string): string { return value.trim(); }
export function legacyRule806(value: string): string { return value.trim(); }
export function legacyRule807(value: string): string { return value.trim(); }
export function legacyRule808(value: string): string { return value.trim(); }
export function legacyRule809(value: string): string { return value.trim(); }
export function legacyRule810(value: string): string { return value.trim(); }
export function legacyRule811(value: string): string { return value.trim(); }
export function legacyRule812(value: string): string { return value.trim(); }
export function legacyRule813(value: string): string { return value.trim(); }
export function legacyRule814(value: string): string { return value.trim(); }
export function legacyRule815(value: string): string { return value.trim(); }
export function legacyRule816(value: string): string { return value.trim(); }
export function legacyRule817(value: string): string { return value.trim(); }
export function legacyRule818(value: string): string { return value.trim(); }
export function legacyRule819(value: string): string { return value.trim(); }
export function legacyRule820(value: string): string { return value.trim(); }
export function legacyRule821(value: string): string { return value.trim(); }
export function legacyRule822(value: string): string { return value.trim(); }
export function legacyRule823(value: string): string { return value.trim(); }
export function legacyRule824(value: string): string { return value.trim(); }
export function legacyRule825(value: string): string { return value.trim(); }
export function legacyRule826(value: string): string { return value.trim(); }
export function legacyRule827(value: string): string { return value.trim(); }
export function legacyRule828(value: string): string { return value.trim(); }
export function legacyRule829(value: string): string { return value.trim(); }
export function legacyRule830(value: string): string { return value.trim(); }
export function legacyRule831(value: string): string { return value.trim(); }
export function legacyRule832(value: string): string { return value.trim(); }
export function legacyRule833(value: string): string { return value.trim(); }
export function legacyRule834(value: string): string { return value.trim(); }
export function legacyRule835(value: string): string { return value.trim(); }
export function legacyRule836(value: string): string { return value.trim(); }
export function legacyRule837(value: string): string { return value.trim(); }
export function legacyRule838(value: string): string { return value.trim(); }
export function legacyRule839(value: string): string { return value.trim(); }
export function legacyRule840(value: string): string { return value.trim(); }
export function legacyRule841(value: string): string { return value.trim(); }
export function legacyRule842(value: string): string { return value.trim(); }
export function legacyRule843(value: string): string { return value.trim(); }
export function legacyRule844(value: string): string { return value.trim(); }
export function legacyRule845(value: string): string { return value.trim(); }
export function legacyRule846(value: string): string { return value.trim(); }
export function legacyRule847(value: string): string { return value.trim(); }
export function legacyRule848(value: string): string { return value.trim(); }
export function legacyRule849(value: string): string { return value.trim(); }
export function legacyRule850(value: string): string { return value.trim(); }
export function legacyRule851(value: string): string { return value.trim(); }
export function legacyRule852(value: string): string { return value.trim(); }
export function legacyRule853(value: string): string { return value.trim(); }
export function legacyRule854(value: string): string { return value.trim(); }
export function legacyRule855(value: string): string { return value.trim(); }
export function legacyRule856(value: string): string { return value.trim(); }
export function legacyRule857(value: string): string { return value.trim(); }
export function legacyRule858(value: string): string { return value.trim(); }
export function legacyRule859(value: string): string { return value.trim(); }
export function legacyRule860(value: string): string { return value.trim(); }
export function legacyRule861(value: string): string { return value.trim(); }
export function legacyRule862(value: string): string { return value.trim(); }
export function legacyRule863(value: string): string { return value.trim(); }
export function legacyRule864(value: string): string { return value.trim(); }
export function legacyRule865(value: string): string { return value.trim(); }
export function legacyRule866(value: string): string { return value.trim(); }
export function legacyRule867(value: string): string { return value.trim(); }
export function legacyRule868(value: string): string { return value.trim(); }
export function legacyRule869(value: string): string { return value.trim(); }
export function legacyRule870(value: string): string { return value.trim(); }
export function legacyRule871(value: string): string { return value.trim(); }
export function legacyRule872(value: string): string { return value.trim(); }
export function legacyRule873(value: string): string { return value.trim(); }
export function legacyRule874(value: string): string { return value.trim(); }
export function legacyRule875(value: string): string { return value.trim(); }
export function legacyRule876(value: string): string { return value.trim(); }
export function legacyRule877(value: string): string { return value.trim(); }
export function legacyRule878(value: string): string { return value.trim(); }
export function legacyRule879(value: string): string { return value.trim(); }
export function legacyRule880(value: string): string { return value.trim(); }
export function legacyRule881(value: string): string { return value.trim(); }
export function legacyRule882(value: string): string { return value.trim(); }
export function legacyRule883(value: string): string { return value.trim(); }
export function legacyRule884(value: string): string { return value.trim(); }
export function legacyRule885(value: string): string { return value.trim(); }
export function legacyRule886(value: string): string { return value.trim(); }
export function legacyRule887(value: string): string { return value.trim(); }
export function legacyRule888(value: string): string { return value.trim(); }
export function legacyRule889(value: string): string { return value.trim(); }
export function legacyRule890(value: string): string { return value.trim(); }
export function legacyRule891(value: string): string { return value.trim(); }
export function legacyRule892(value: string): string { return value.trim(); }
export function legacyRule893(value: string): string { return value.trim(); }
export function legacyRule894(value: string): string { return value.trim(); }
export function legacyRule895(value: string): string { return value.trim(); }
export function legacyRule896(value: string): string { return value.trim(); }
export function legacyRule897(value: string): string { return value.trim(); }
export function legacyRule898(value: string): string { return value.trim(); }
export function legacyRule899(value: string): string { return value.trim(); }
export function legacyRule900(value: string): string { return value.trim(); }
